# Generated by Django 3.0.5 on 2020-04-26 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=1024, verbose_name='Address Line 1')),
                ('line_two', models.CharField(blank=True, max_length=1024, verbose_name='Address Line 2')),
                ('city', models.CharField(blank=True, max_length=1024, verbose_name='City')),
                ('region_state', models.CharField(blank=True, max_length=1024, verbose_name='State')),
                ('code', models.CharField(blank=True, max_length=1024, verbose_name='Zipcode')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='UserQuestionnaire',
            fields=[
                ('user_id', models.CharField(max_length=1024, primary_key=True, serialize=False, verbose_name='User identifier')),
                ('wants_questionnaire', models.BooleanField(default=None, null=True)),
                ('is_experiencing_symptoms', models.BooleanField(default=None, null=True)),
                ('is_high_risk', models.BooleanField(default=None, null=True)),
                ('has_severe_worsening_symptoms', models.BooleanField(default=None, null=True)),
                ('preferred_testing_site_type', models.CharField(choices=[('WU', 'Walk up'), ('DT', 'Drive Through')], default=None, max_length=2, null=True)),
                ('zip_code', models.CharField(default=None, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestingSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=1024, verbose_name='Phone Number')),
                ('name', models.CharField(max_length=1024, verbose_name='Testing Site Name')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Address', verbose_name='Address')),
            ],
        ),
    ]
