# Generated by Django 3.0.5 on 2020-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionnaire',
            name='last_message_sent',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
