# Generated by Django 3.0.5 on 2020-04-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userquestionnaire_last_message_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='is_high_risk',
        ),
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='preferred_testing_site_type',
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='can_get_provider_test',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
