# Generated by Django 3.0.5 on 2020-05-17 00:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200426_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testingsite',
            old_name='name',
            new_name='site_name',
        ),
        migrations.RemoveField(
            model_name='testingsite',
            name='phone',
        ),
        migrations.AddField(
            model_name='testingsite',
            name='provider_name',
            field=models.CharField(default='default name', max_length=1024, verbose_name='Testing Site Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testingsite',
            name='provider_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact Provider to schedule test', max_length=31),
        ),
        migrations.AddField(
            model_name='testingsite',
            name='site_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact Provider to schedule test', max_length=31),
        ),
    ]
