# Generated by Django 3.0.5 on 2020-05-23 21:05

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200517_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=1024, verbose_name='Testing Provider Name')),
                ('provider_phone', phone_field.models.PhoneField(blank=True, help_text='Contact Provider to schedule test', max_length=31)),
                ('provider_alt_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
            ],
        ),
        migrations.RemoveField(
            model_name='testingsite',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='testingsite',
            name='provider_phone',
        ),
        migrations.AddField(
            model_name='testingsite',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Provider'),
        ),
    ]
