# Generated by Django 3.0.5 on 2020-07-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200616_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionnaire',
            name='next_response',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userquestionnaire',
            name='result_index',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
