# Generated by Django 3.0.5 on 2020-07-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200719_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquestionnaire',
            name='next_response',
        ),
    ]
