version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "80:8000"
    command: python ReachCare/manage.py runserver_plus 0.0.0.0:8000 --key-file .ssl-key
    environment:
      - DATABASE_NAME=${POSTGRES_DB}
      - DATABASE_USER=${POSTGRES_USER}
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS
    volumes:
      - .ssl-key:.ssl-key
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ${DATABASE_DATA_ROOT}:/var/lib/postgresql/data
    ports:
      - 5432:5432

